packages:
  - packages/*

catalog:
  typescript: ^5.9.3
  unbuild: 3.6.1
  eslint: ^9.39.2
  "@eslint/js": ^9.39.2
  typescript-eslint: ^8.50.0
  vitest: ^4.0.16
  rollup: ^4.27.0
  "@rollup/plugin-typescript": ^12.1.0
  "@rollup/plugin-node-resolve": ^15.3.0
  "@rollup/plugin-commonjs": ^28.0.1
